### ISSUE TITLE
PRACTIVA 9 ACTIVIDAD 6

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-9-practica-6-contrato-compilado-sistematosaurias#1]
[ACTIVIDAD 9 PRACTICA 6.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-6-contrato-compilado-sistematosaurias/files/15380931/ACTIVIDAD.9.PRACTICA.6.pdf)

**Comment by josealfredo79** [comment]
No se puede visualizar en el reporte de la practica que se ejecuten en consola los metodos o funciones del contrato..por favor de modificar para poder evaluar...

**Comment by josealfredo79** [comment]
Bien hecho y revisao...Calificacion. 18
